version: '3.9'
services:
  mongo:
    image: arm64v8/mongo
    restart: on-failure
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./mongo-data:/data
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: "--replSet rs0"
  example:
    image: pv2-example 
    volumes:
      - ./node_modules:/app/node_modules
    ports:
      - 1984:1984
    environment:
      - PROVIDERS_DATABASE_MONGO_INSTANCES_0_CONNECTION_STRING=mongodb://mongo:27017
    command: node index.js